version: "2"

services:
  ros_echo:
    build:
      context: ../..
      dockerfile: docker_scripts/jetson/jetsonDockerfile
    # network_mode: "host"
    # pid: "host"
    ports:
      - "9090:9090"
    command: tail -F anything # will run container forever
