version: '3.3'

services:
  robotics:
    build:
      context: ./
      dockerfile: robotics.Dockerfile
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XDG_RUNTIME_DIR:/tmp/runtime-root
    command: tail -F anything # will run container forever
